// Code generated by protoc-gen-typescript-http. DO NOT EDIT.
/* eslint-disable camelcase */
// @ts-nocheck

// User is the user message.
export type User = {
  // The unique ID of the user.
  id: number | undefined;
  // The name of the user.
  name: string | undefined;
  // The email of the user.
  email: string | undefined;
  // The avatar URL of the user.
  avatar: string | undefined;
};

// LoginRequest is the request message for the Login method.
export type LoginRequest = {
  // Username of the user.
  username: string | undefined;
  // Password of the user.
  password: string | undefined;
};

// The Auth service definition.
export interface Auth {
  // Login a user and return the username.
  Login(request: LoginRequest): Promise<User>;
  // Current returns the currently logged-in user.
  Current(request: wellKnownEmpty): Promise<User>;
  // Logout the currently logged-in user.
  Logout(request: wellKnownEmpty): Promise<wellKnownEmpty>;
}

type RequestType = {
  path: string;
  method: string;
  body: string | null;
};

type RequestHandler = (request: RequestType, meta: { service: string, method: string }) => Promise<unknown>;

export function createAuthClient(
  handler: RequestHandler
): Auth {
  return {
    Login(request) { // eslint-disable-line @typescript-eslint/no-unused-vars
      const path = `v1/auths/login`; // eslint-disable-line quotes
      const body = JSON.stringify(request);
      const queryParams: string[] = [];
      let uri = path;
      if (queryParams.length > 0) {
        uri += `?${queryParams.join("&")}`
      }
      return handler({
        path: uri,
        method: "POST",
        body,
      }, {
        service: "Auth",
        method: "Login",
      }) as Promise<User>;
    },
    Current(request) { // eslint-disable-line @typescript-eslint/no-unused-vars
      const path = `v1/auths/current`; // eslint-disable-line quotes
      const body = null;
      const queryParams: string[] = [];
      let uri = path;
      if (queryParams.length > 0) {
        uri += `?${queryParams.join("&")}`
      }
      return handler({
        path: uri,
        method: "GET",
        body,
      }, {
        service: "Auth",
        method: "Current",
      }) as Promise<User>;
    },
    Logout(request) { // eslint-disable-line @typescript-eslint/no-unused-vars
      const path = `v1/auths/logout`; // eslint-disable-line quotes
      const body = JSON.stringify(request);
      const queryParams: string[] = [];
      let uri = path;
      if (queryParams.length > 0) {
        uri += `?${queryParams.join("&")}`
      }
      return handler({
        path: uri,
        method: "POST",
        body,
      }, {
        service: "Auth",
        method: "Logout",
      }) as Promise<wellKnownEmpty>;
    },
  };
}
// An empty JSON object
type wellKnownEmpty = Record<never, never>;


// @@protoc_insertion_point(typescript-http-eof)
