// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: kratos/admin/v1/admin.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	fieldmaskpb "google.golang.org/protobuf/types/known/fieldmaskpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Status is the lifecycle status of an admin. `DELETED` marks a soft-deleted
// record: it stays in storage but is excluded from reads.
type Admin_Status int32

const (
	// Unset. On create the server stores `ACTIVE`; on update it leaves the
	// stored status unchanged.
	Admin_STATUS_UNSPECIFIED Admin_Status = 0
	// The admin is in normal use.
	Admin_ACTIVE Admin_Status = 1
	// The admin is disabled.
	Admin_INACTIVE Admin_Status = 2
	// The admin is soft-deleted.
	Admin_DELETED Admin_Status = 3
)

// Enum value maps for Admin_Status.
var (
	Admin_Status_name = map[int32]string{
		0: "STATUS_UNSPECIFIED",
		1: "ACTIVE",
		2: "INACTIVE",
		3: "DELETED",
	}
	Admin_Status_value = map[string]int32{
		"STATUS_UNSPECIFIED": 0,
		"ACTIVE":             1,
		"INACTIVE":           2,
		"DELETED":            3,
	}
)

func (x Admin_Status) Enum() *Admin_Status {
	p := new(Admin_Status)
	*p = x
	return p
}

func (x Admin_Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Admin_Status) Descriptor() protoreflect.EnumDescriptor {
	return file_kratos_admin_v1_admin_proto_enumTypes[0].Descriptor()
}

func (Admin_Status) Type() protoreflect.EnumType {
	return &file_kratos_admin_v1_admin_proto_enumTypes[0]
}

func (x Admin_Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Admin_Status.Descriptor instead.
func (Admin_Status) EnumDescriptor() ([]byte, []int) {
	return file_kratos_admin_v1_admin_proto_rawDescGZIP(), []int{0, 0}
}

// Admin is the admin message.
type Admin struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The unique ID of the user, a UUID assigned by the server.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// The name of the user.
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// The email of the user.
	Email string `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	// The phone number of the user.
	Phone string `protobuf:"bytes,4,opt,name=phone,proto3" json:"phone,omitempty"`
	// The avatar URL of the user.
	Avatar string `protobuf:"bytes,5,opt,name=avatar,proto3" json:"avatar,omitempty"`
	// The access level of the user.
	// Possible values are: "admin", "user", etc.
	Access string `protobuf:"bytes,6,opt,name=access,proto3" json:"access,omitempty"`
	// The password of the user.
	Password string `protobuf:"bytes,7,opt,name=password,proto3" json:"password,omitempty"`
	// The timestamp at which the user was created.
	CreatedAt *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// The latest timestamp at which the user was updated.
	UpdatedAt *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	// The lifecycle status of the user.
	Status        Admin_Status `protobuf:"varint,10,opt,name=status,proto3,enum=kratos.admin.v1.Admin_Status" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Admin) Reset() {
	*x = Admin{}
	mi := &file_kratos_admin_v1_admin_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Admin) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Admin) ProtoMessage() {}

func (x *Admin) ProtoReflect() protoreflect.Message {
	mi := &file_kratos_admin_v1_admin_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Admin.ProtoReflect.Descriptor instead.
func (*Admin) Descriptor() ([]byte, []int) {
	return file_kratos_admin_v1_admin_proto_rawDescGZIP(), []int{0}
}

func (x *Admin) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Admin) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Admin) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *Admin) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *Admin) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *Admin) GetAccess() string {
	if x != nil {
		return x.Access
	}
	return ""
}

func (x *Admin) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *Admin) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Admin) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *Admin) GetStatus() Admin_Status {
	if x != nil {
		return x.Status
	}
	return Admin_STATUS_UNSPECIFIED
}

// AdminSet is the set of admins.
type AdminSet struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The set of admins.
	Admins []*Admin `protobuf:"bytes,1,rep,name=admins,proto3" json:"admins,omitempty"`
	// The next page token.
	NextPageToken string `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminSet) Reset() {
	*x = AdminSet{}
	mi := &file_kratos_admin_v1_admin_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminSet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminSet) ProtoMessage() {}

func (x *AdminSet) ProtoReflect() protoreflect.Message {
	mi := &file_kratos_admin_v1_admin_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminSet.ProtoReflect.Descriptor instead.
func (*AdminSet) Descriptor() ([]byte, []int) {
	return file_kratos_admin_v1_admin_proto_rawDescGZIP(), []int{1}
}

func (x *AdminSet) GetAdmins() []*Admin {
	if x != nil {
		return x.Admins
	}
	return nil
}

func (x *AdminSet) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

// LoginRequest is the request message for the Login method.
type LoginRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Required. Password of the user.
	Password string `protobuf:"bytes,1,opt,name=password,proto3" json:"password,omitempty"`
	// Required. Exactly one identity must be set.
	//
	// Types that are valid to be assigned to Identity:
	//
	//	*LoginRequest_Username
	//	*LoginRequest_Email
	Identity      isLoginRequest_Identity `protobuf_oneof:"identity"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginRequest) Reset() {
	*x = LoginRequest{}
	mi := &file_kratos_admin_v1_admin_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRequest) ProtoMessage() {}

func (x *LoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kratos_admin_v1_admin_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRequest.ProtoReflect.Descriptor instead.
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return file_kratos_admin_v1_admin_proto_rawDescGZIP(), []int{2}
}

func (x *LoginRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *LoginRequest) GetIdentity() isLoginRequest_Identity {
	if x != nil {
		return x.Identity
	}
	return nil
}

func (x *LoginRequest) GetUsername() string {
	if x != nil {
		if x, ok := x.Identity.(*LoginRequest_Username); ok {
			return x.Username
		}
	}
	return ""
}

func (x *LoginRequest) GetEmail() string {
	if x != nil {
		if x, ok := x.Identity.(*LoginRequest_Email); ok {
			return x.Email
		}
	}
	return ""
}

type isLoginRequest_Identity interface {
	isLoginRequest_Identity()
}

type LoginRequest_Username struct {
	Username string `protobuf:"bytes,2,opt,name=username,proto3,oneof"`
}

type LoginRequest_Email struct {
	Email string `protobuf:"bytes,3,opt,name=email,proto3,oneof"`
}

func (*LoginRequest_Username) isLoginRequest_Identity() {}

func (*LoginRequest_Email) isLoginRequest_Identity() {}

// GetAdminRequest is the request message for the GetAdmin method.
type GetAdminRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The ID of the admin to retrieve.
	Id            string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAdminRequest) Reset() {
	*x = GetAdminRequest{}
	mi := &file_kratos_admin_v1_admin_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAdminRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAdminRequest) ProtoMessage() {}

func (x *GetAdminRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kratos_admin_v1_admin_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAdminRequest.ProtoReflect.Descriptor instead.
func (*GetAdminRequest) Descriptor() ([]byte, []int) {
	return file_kratos_admin_v1_admin_proto_rawDescGZIP(), []int{3}
}

func (x *GetAdminRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// ListAdminsResponse is the response message for the ListAdmins method.
type ListAdminsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Optional. The number of admins per page.
	PageSize int32 `protobuf:"varint,1,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	// Optional. The page token.
	PageToken string `protobuf:"bytes,2,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	// Optional. The standard list filter.
	// Supported fields:
	//   - `name` (i.e. `name="John Doe"`)
	//   - `email` (i.e. `email="admin@go-kratos.dev"`)
	//   - `phone` (i.e. `phone="+1234567890"`)
	//   - `created_at` range (i.e. `timestamp>="2025-01-31T11:30:00-04:00"` where
	//     the timestamp is in RFC 3339 format)
	//
	// Soft-deleted admins are never returned, regardless of filter.
	//
	// More detail in [AIP-160](https://google.aip.dev/160).
	Filter string `protobuf:"bytes,3,opt,name=filter,proto3" json:"filter,omitempty"`
	// Optional. A comma-separated list of fields to order by, sorted in ascending
	// order. Use "desc" after a field name for descending. Supported fields:
	// - `created_at`
	//
	// Example: `created_at desc`.
	OrderBy       string `protobuf:"bytes,4,opt,name=order_by,json=orderBy,proto3" json:"order_by,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAdminsRequest) Reset() {
	*x = ListAdminsRequest{}
	mi := &file_kratos_admin_v1_admin_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAdminsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAdminsRequest) ProtoMessage() {}

func (x *ListAdminsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kratos_admin_v1_admin_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAdminsRequest.ProtoReflect.Descriptor instead.
func (*ListAdminsRequest) Descriptor() ([]byte, []int) {
	return file_kratos_admin_v1_admin_proto_rawDescGZIP(), []int{4}
}

func (x *ListAdminsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListAdminsRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

func (x *ListAdminsRequest) GetFilter() string {
	if x != nil {
		return x.Filter
	}
	return ""
}

func (x *ListAdminsRequest) GetOrderBy() string {
	if x != nil {
		return x.OrderBy
	}
	return ""
}

// CreateAdminRequest is the request message for the CreateAdmin method.
type CreateAdminRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Required. The admin to create.
	Admin         *Admin `protobuf:"bytes,1,opt,name=admin,proto3" json:"admin,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAdminRequest) Reset() {
	*x = CreateAdminRequest{}
	mi := &file_kratos_admin_v1_admin_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAdminRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAdminRequest) ProtoMessage() {}

func (x *CreateAdminRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kratos_admin_v1_admin_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAdminRequest.ProtoReflect.Descriptor instead.
func (*CreateAdminRequest) Descriptor() ([]byte, []int) {
	return file_kratos_admin_v1_admin_proto_rawDescGZIP(), []int{5}
}

func (x *CreateAdminRequest) GetAdmin() *Admin {
	if x != nil {
		return x.Admin
	}
	return nil
}

// UpdateAdminRequest is the request message for the UpdateAdmin method.
type UpdateAdminRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Required. The admin to update.
	Admin *Admin `protobuf:"bytes,1,opt,name=admin,proto3" json:"admin,omitempty"`
	// Required. Mask of fields to update.
	UpdateMask    *fieldmaskpb.FieldMask `protobuf:"bytes,2,opt,name=update_mask,json=updateMask,proto3" json:"update_mask,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateAdminRequest) Reset() {
	*x = UpdateAdminRequest{}
	mi := &file_kratos_admin_v1_admin_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateAdminRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAdminRequest) ProtoMessage() {}

func (x *UpdateAdminRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kratos_admin_v1_admin_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAdminRequest.ProtoReflect.Descriptor instead.
func (*UpdateAdminRequest) Descriptor() ([]byte, []int) {
	return file_kratos_admin_v1_admin_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateAdminRequest) GetAdmin() *Admin {
	if x != nil {
		return x.Admin
	}
	return nil
}

func (x *UpdateAdminRequest) GetUpdateMask() *fieldmaskpb.FieldMask {
	if x != nil {
		return x.UpdateMask
	}
	return nil
}

// DeleteAdminRequest is the request message for the DeleteAdmin method.
type DeleteAdminRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Required. The ID of the admin to delete. The record is soft-deleted: its
	// status becomes `DELETED` and it no longer appears in reads.
	Id            string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteAdminRequest) Reset() {
	*x = DeleteAdminRequest{}
	mi := &file_kratos_admin_v1_admin_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteAdminRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAdminRequest) ProtoMessage() {}

func (x *DeleteAdminRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kratos_admin_v1_admin_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAdminRequest.ProtoReflect.Descriptor instead.
func (*DeleteAdminRequest) Descriptor() ([]byte, []int) {
	return file_kratos_admin_v1_admin_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteAdminRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

var File_kratos_admin_v1_admin_proto protoreflect.FileDescriptor

const file_kratos_admin_v1_admin_proto_rawDesc = "" +
	"\n" +
	"\x1bkratos/admin/v1/admin.proto\x12\x0fkratos.admin.v1\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a google/protobuf/field_mask.proto\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/api/field_behavior.proto\"\x99\x03\n" +
	"\x05Admin\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12\x14\n" +
	"\x05phone\x18\x04 \x01(\tR\x05phone\x12\x16\n" +
	"\x06avatar\x18\x05 \x01(\tR\x06avatar\x12\x16\n" +
	"\x06access\x18\x06 \x01(\tR\x06access\x12\x1a\n" +
	"\bpassword\x18\a \x01(\tR\bpassword\x129\n" +
	"\n" +
	"created_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x125\n" +
	"\x06status\x18\n" +
	" \x01(\x0e2\x1d.kratos.admin.v1.Admin.StatusR\x06status\"G\n" +
	"\x06Status\x12\x16\n" +
	"\x12STATUS_UNSPECIFIED\x10\x00\x12\n" +
	"\n" +
	"\x06ACTIVE\x10\x01\x12\f\n" +
	"\bINACTIVE\x10\x02\x12\v\n" +
	"\aDELETED\x10\x03\"b\n" +
	"\bAdminSet\x12.\n" +
	"\x06admins\x18\x01 \x03(\v2\x16.kratos.admin.v1.AdminR\x06admins\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\"q\n" +
	"\fLoginRequest\x12\x1f\n" +
	"\bpassword\x18\x01 \x01(\tB\x03\xe0A\x02R\bpassword\x12\x1c\n" +
	"\busername\x18\x02 \x01(\tH\x00R\busername\x12\x16\n" +
	"\x05email\x18\x03 \x01(\tH\x00R\x05emailB\n" +
	"\n" +
	"\bidentity\"&\n" +
	"\x0fGetAdminRequest\x12\x13\n" +
	"\x02id\x18\x01 \x01(\tB\x03\xe0A\x02R\x02id\"\x82\x01\n" +
	"\x11ListAdminsRequest\x12\x1b\n" +
	"\tpage_size\x18\x01 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x02 \x01(\tR\tpageToken\x12\x16\n" +
	"\x06filter\x18\x03 \x01(\tR\x06filter\x12\x19\n" +
	"\border_by\x18\x04 \x01(\tR\aorderBy\"G\n" +
	"\x12CreateAdminRequest\x121\n" +
	"\x05admin\x18\x01 \x01(\v2\x16.kratos.admin.v1.AdminB\x03\xe0A\x02R\x05admin\"\x89\x01\n" +
	"\x12UpdateAdminRequest\x121\n" +
	"\x05admin\x18\x01 \x01(\v2\x16.kratos.admin.v1.AdminB\x03\xe0A\x02R\x05admin\x12@\n" +
	"\vupdate_mask\x18\x02 \x01(\v2\x1a.google.protobuf.FieldMaskB\x03\xe0A\x02R\n" +
	"updateMask\")\n" +
	"\x12DeleteAdminRequest\x12\x13\n" +
	"\x02id\x18\x01 \x01(\tB\x03\xe0A\x02R\x02id2\xa0\x06\n" +
	"\fAdminService\x12[\n" +
	"\x05Login\x12\x1d.kratos.admin.v1.LoginRequest\x1a\x16.kratos.admin.v1.Admin\"\x1b\x82\xd3\xe4\x93\x02\x15:\x01*\"\x10/v1/admins/login\x12V\n" +
	"\x06Logout\x12\x16.google.protobuf.Empty\x1a\x16.google.protobuf.Empty\"\x1c\x82\xd3\xe4\x93\x02\x16:\x01*\"\x11/v1/admins/logout\x12U\n" +
	"\aCurrent\x12\x16.google.protobuf.Empty\x1a\x16.kratos.admin.v1.Admin\"\x1a\x82\xd3\xe4\x93\x02\x14\x12\x12/v1/admins/current\x12d\n" +
	"\n" +
	"ListAdmins\x12\".kratos.admin.v1.ListAdminsRequest\x1a\x19.kratos.admin.v1.AdminSet\"\x17\x82\xd3\xe4\x93\x02\x11\x12\x0f/v1/admins/list\x12l\n" +
	"\vCreateAdmin\x12#.kratos.admin.v1.CreateAdminRequest\x1a\x16.kratos.admin.v1.Admin\" \x82\xd3\xe4\x93\x02\x1a:\x05admin\"\x11/v1/admins/create\x12l\n" +
	"\vUpdateAdmin\x12#.kratos.admin.v1.UpdateAdminRequest\x1a\x16.kratos.admin.v1.Admin\" \x82\xd3\xe4\x93\x02\x1a:\x05admin\x1a\x11/v1/admins/update\x12c\n" +
	"\vDeleteAdmin\x12#.kratos.admin.v1.DeleteAdminRequest\x1a\x16.google.protobuf.Empty\"\x17\x82\xd3\xe4\x93\x02\x11*\x0f/v1/admins/{id}\x12]\n" +
	"\bGetAdmin\x12 .kratos.admin.v1.GetAdminRequest\x1a\x16.kratos.admin.v1.Admin\"\x17\x82\xd3\xe4\x93\x02\x11\x12\x0f/v1/admins/{id}BQ\n" +
	"\x13api.kratos.admin.v1P\x01Z8github.com/go-kratos/kratos-admin/api/kratos/admin/v1;v1b\x06proto3"

var (
	file_kratos_admin_v1_admin_proto_rawDescOnce sync.Once
	file_kratos_admin_v1_admin_proto_rawDescData []byte
)

func file_kratos_admin_v1_admin_proto_rawDescGZIP() []byte {
	file_kratos_admin_v1_admin_proto_rawDescOnce.Do(func() {
		file_kratos_admin_v1_admin_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_kratos_admin_v1_admin_proto_rawDesc), len(file_kratos_admin_v1_admin_proto_rawDesc)))
	})
	return file_kratos_admin_v1_admin_proto_rawDescData
}

var file_kratos_admin_v1_admin_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_kratos_admin_v1_admin_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_kratos_admin_v1_admin_proto_goTypes = []any{
	(Admin_Status)(0),             // 0: kratos.admin.v1.Admin.Status
	(*Admin)(nil),                 // 1: kratos.admin.v1.Admin
	(*AdminSet)(nil),              // 2: kratos.admin.v1.AdminSet
	(*LoginRequest)(nil),          // 3: kratos.admin.v1.LoginRequest
	(*GetAdminRequest)(nil),       // 4: kratos.admin.v1.GetAdminRequest
	(*ListAdminsRequest)(nil),     // 5: kratos.admin.v1.ListAdminsRequest
	(*CreateAdminRequest)(nil),    // 6: kratos.admin.v1.CreateAdminRequest
	(*UpdateAdminRequest)(nil),    // 7: kratos.admin.v1.UpdateAdminRequest
	(*DeleteAdminRequest)(nil),    // 8: kratos.admin.v1.DeleteAdminRequest
	(*timestamppb.Timestamp)(nil), // 9: google.protobuf.Timestamp
	(*fieldmaskpb.FieldMask)(nil), // 10: google.protobuf.FieldMask
	(*emptypb.Empty)(nil),         // 11: google.protobuf.Empty
}
var file_kratos_admin_v1_admin_proto_depIdxs = []int32{
	9,  // 0: kratos.admin.v1.Admin.created_at:type_name -> google.protobuf.Timestamp
	9,  // 1: kratos.admin.v1.Admin.updated_at:type_name -> google.protobuf.Timestamp
	0,  // 2: kratos.admin.v1.Admin.status:type_name -> kratos.admin.v1.Admin.Status
	1,  // 3: kratos.admin.v1.AdminSet.admins:type_name -> kratos.admin.v1.Admin
	1,  // 4: kratos.admin.v1.CreateAdminRequest.admin:type_name -> kratos.admin.v1.Admin
	1,  // 5: kratos.admin.v1.UpdateAdminRequest.admin:type_name -> kratos.admin.v1.Admin
	10, // 6: kratos.admin.v1.UpdateAdminRequest.update_mask:type_name -> google.protobuf.FieldMask
	3,  // 7: kratos.admin.v1.AdminService.Login:input_type -> kratos.admin.v1.LoginRequest
	11, // 8: kratos.admin.v1.AdminService.Logout:input_type -> google.protobuf.Empty
	11, // 9: kratos.admin.v1.AdminService.Current:input_type -> google.protobuf.Empty
	5,  // 10: kratos.admin.v1.AdminService.ListAdmins:input_type -> kratos.admin.v1.ListAdminsRequest
	6,  // 11: kratos.admin.v1.AdminService.CreateAdmin:input_type -> kratos.admin.v1.CreateAdminRequest
	7,  // 12: kratos.admin.v1.AdminService.UpdateAdmin:input_type -> kratos.admin.v1.UpdateAdminRequest
	8,  // 13: kratos.admin.v1.AdminService.DeleteAdmin:input_type -> kratos.admin.v1.DeleteAdminRequest
	4,  // 14: kratos.admin.v1.AdminService.GetAdmin:input_type -> kratos.admin.v1.GetAdminRequest
	1,  // 15: kratos.admin.v1.AdminService.Login:output_type -> kratos.admin.v1.Admin
	11, // 16: kratos.admin.v1.AdminService.Logout:output_type -> google.protobuf.Empty
	1,  // 17: kratos.admin.v1.AdminService.Current:output_type -> kratos.admin.v1.Admin
	2,  // 18: kratos.admin.v1.AdminService.ListAdmins:output_type -> kratos.admin.v1.AdminSet
	1,  // 19: kratos.admin.v1.AdminService.CreateAdmin:output_type -> kratos.admin.v1.Admin
	1,  // 20: kratos.admin.v1.AdminService.UpdateAdmin:output_type -> kratos.admin.v1.Admin
	11, // 21: kratos.admin.v1.AdminService.DeleteAdmin:output_type -> google.protobuf.Empty
	1,  // 22: kratos.admin.v1.AdminService.GetAdmin:output_type -> kratos.admin.v1.Admin
	15, // [15:23] is the sub-list for method output_type
	7,  // [7:15] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_kratos_admin_v1_admin_proto_init() }
func file_kratos_admin_v1_admin_proto_init() {
	if File_kratos_admin_v1_admin_proto != nil {
		return
	}
	file_kratos_admin_v1_admin_proto_msgTypes[2].OneofWrappers = []any{
		(*LoginRequest_Username)(nil),
		(*LoginRequest_Email)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_kratos_admin_v1_admin_proto_rawDesc), len(file_kratos_admin_v1_admin_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_kratos_admin_v1_admin_proto_goTypes,
		DependencyIndexes: file_kratos_admin_v1_admin_proto_depIdxs,
		EnumInfos:         file_kratos_admin_v1_admin_proto_enumTypes,
		MessageInfos:      file_kratos_admin_v1_admin_proto_msgTypes,
	}.Build()
	File_kratos_admin_v1_admin_proto = out.File
	file_kratos_admin_v1_admin_proto_goTypes = nil
	file_kratos_admin_v1_admin_proto_depIdxs = nil
}
