// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v4.23.2
// source: kratos/admin/v1/auth.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// User is the user message.
type User struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The unique ID of the user.
	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// The name of the user.
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// The email of the user.
	Email string `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	// The avatar URL of the user.
	Avatar        string `protobuf:"bytes,4,opt,name=avatar,proto3" json:"avatar,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_kratos_admin_v1_auth_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_kratos_admin_v1_auth_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_kratos_admin_v1_auth_proto_rawDescGZIP(), []int{0}
}

func (x *User) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *User) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *User) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *User) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

// LoginRequest is the request message for the Login method.
type LoginRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Username of the user.
	Username string `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	// Password of the user.
	Password      string `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginRequest) Reset() {
	*x = LoginRequest{}
	mi := &file_kratos_admin_v1_auth_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRequest) ProtoMessage() {}

func (x *LoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kratos_admin_v1_auth_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRequest.ProtoReflect.Descriptor instead.
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return file_kratos_admin_v1_auth_proto_rawDescGZIP(), []int{1}
}

func (x *LoginRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *LoginRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

var File_kratos_admin_v1_auth_proto protoreflect.FileDescriptor

const file_kratos_admin_v1_auth_proto_rawDesc = "" +
	"\n" +
	"\x1akratos/admin/v1/auth.proto\x12\x0fkratos.admin.v1\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1cgoogle/api/annotations.proto\"X\n" +
	"\x04User\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12\x16\n" +
	"\x06avatar\x18\x04 \x01(\tR\x06avatar\"F\n" +
	"\fLoginRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword2\x8d\x02\n" +
	"\x04Auth\x12Y\n" +
	"\x05Login\x12\x1d.kratos.admin.v1.LoginRequest\x1a\x15.kratos.admin.v1.User\"\x1a\x82\xd3\xe4\x93\x02\x14:\x01*\"\x0f/v1/auths/login\x12S\n" +
	"\aCurrent\x12\x16.google.protobuf.Empty\x1a\x15.kratos.admin.v1.User\"\x19\x82\xd3\xe4\x93\x02\x13\x12\x11/v1/auths/current\x12U\n" +
	"\x06Logout\x12\x16.google.protobuf.Empty\x1a\x16.google.protobuf.Empty\"\x1b\x82\xd3\xe4\x93\x02\x15:\x01*\"\x10/v1/auths/logoutB\\\n" +
	"\x13api.kratos.admin.v1B\tAuthProtoP\x01Z8github.com/go-kratos/kratos-admin/api/kratos/admin/v1;v1b\x06proto3"

var (
	file_kratos_admin_v1_auth_proto_rawDescOnce sync.Once
	file_kratos_admin_v1_auth_proto_rawDescData []byte
)

func file_kratos_admin_v1_auth_proto_rawDescGZIP() []byte {
	file_kratos_admin_v1_auth_proto_rawDescOnce.Do(func() {
		file_kratos_admin_v1_auth_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_kratos_admin_v1_auth_proto_rawDesc), len(file_kratos_admin_v1_auth_proto_rawDesc)))
	})
	return file_kratos_admin_v1_auth_proto_rawDescData
}

var file_kratos_admin_v1_auth_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_kratos_admin_v1_auth_proto_goTypes = []any{
	(*User)(nil),          // 0: kratos.admin.v1.User
	(*LoginRequest)(nil),  // 1: kratos.admin.v1.LoginRequest
	(*emptypb.Empty)(nil), // 2: google.protobuf.Empty
}
var file_kratos_admin_v1_auth_proto_depIdxs = []int32{
	1, // 0: kratos.admin.v1.Auth.Login:input_type -> kratos.admin.v1.LoginRequest
	2, // 1: kratos.admin.v1.Auth.Current:input_type -> google.protobuf.Empty
	2, // 2: kratos.admin.v1.Auth.Logout:input_type -> google.protobuf.Empty
	0, // 3: kratos.admin.v1.Auth.Login:output_type -> kratos.admin.v1.User
	0, // 4: kratos.admin.v1.Auth.Current:output_type -> kratos.admin.v1.User
	2, // 5: kratos.admin.v1.Auth.Logout:output_type -> google.protobuf.Empty
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_kratos_admin_v1_auth_proto_init() }
func file_kratos_admin_v1_auth_proto_init() {
	if File_kratos_admin_v1_auth_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_kratos_admin_v1_auth_proto_rawDesc), len(file_kratos_admin_v1_auth_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_kratos_admin_v1_auth_proto_goTypes,
		DependencyIndexes: file_kratos_admin_v1_auth_proto_depIdxs,
		MessageInfos:      file_kratos_admin_v1_auth_proto_msgTypes,
	}.Build()
	File_kratos_admin_v1_auth_proto = out.File
	file_kratos_admin_v1_auth_proto_goTypes = nil
	file_kratos_admin_v1_auth_proto_depIdxs = nil
}
