// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: kratos/admin/v1/error_reason.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ErrorReason is the stable vocabulary for the `reason` field of the error
// body. Values are wire-visible: protojson encodes them as their names, so
// clients branch on the name (e.g. "ADMIN_NOT_FOUND") rather than on an HTTP
// status. Surfaced in `biz` as `Err<Resource><Cause>`.
type ErrorReason int32

const (
	// Unset. Never returned; reserved by proto3 for the zero value.
	ErrorReason_ERROR_REASON_UNSPECIFIED ErrorReason = 0
	// The requested admin does not exist.
	ErrorReason_ADMIN_NOT_FOUND ErrorReason = 1
	// Login failed. Returned for both an unknown account and a wrong password
	// so callers cannot probe which accounts are registered.
	ErrorReason_INVALID_CREDENTIALS ErrorReason = 2
	// The login request carried no identity, or one this server does not accept.
	ErrorReason_INVALID_IDENTITY_TYPE ErrorReason = 3
	// The request carried no usable credential (missing or invalid token).
	ErrorReason_UNAUTHENTICATED ErrorReason = 4
	// The caller is authenticated but lacks the required access level.
	ErrorReason_PERMISSION_DENIED ErrorReason = 5
	// The request carried an admin ID that is not a valid UUID.
	ErrorReason_INVALID_ADMIN_ID ErrorReason = 6
)

// Enum value maps for ErrorReason.
var (
	ErrorReason_name = map[int32]string{
		0: "ERROR_REASON_UNSPECIFIED",
		1: "ADMIN_NOT_FOUND",
		2: "INVALID_CREDENTIALS",
		3: "INVALID_IDENTITY_TYPE",
		4: "UNAUTHENTICATED",
		5: "PERMISSION_DENIED",
		6: "INVALID_ADMIN_ID",
	}
	ErrorReason_value = map[string]int32{
		"ERROR_REASON_UNSPECIFIED": 0,
		"ADMIN_NOT_FOUND":          1,
		"INVALID_CREDENTIALS":      2,
		"INVALID_IDENTITY_TYPE":    3,
		"UNAUTHENTICATED":          4,
		"PERMISSION_DENIED":        5,
		"INVALID_ADMIN_ID":         6,
	}
)

func (x ErrorReason) Enum() *ErrorReason {
	p := new(ErrorReason)
	*p = x
	return p
}

func (x ErrorReason) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ErrorReason) Descriptor() protoreflect.EnumDescriptor {
	return file_kratos_admin_v1_error_reason_proto_enumTypes[0].Descriptor()
}

func (ErrorReason) Type() protoreflect.EnumType {
	return &file_kratos_admin_v1_error_reason_proto_enumTypes[0]
}

func (x ErrorReason) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ErrorReason.Descriptor instead.
func (ErrorReason) EnumDescriptor() ([]byte, []int) {
	return file_kratos_admin_v1_error_reason_proto_rawDescGZIP(), []int{0}
}

var File_kratos_admin_v1_error_reason_proto protoreflect.FileDescriptor

const file_kratos_admin_v1_error_reason_proto_rawDesc = "" +
	"\n" +
	"\"kratos/admin/v1/error_reason.proto\x12\x0fkratos.admin.v1*\xb6\x01\n" +
	"\vErrorReason\x12\x1c\n" +
	"\x18ERROR_REASON_UNSPECIFIED\x10\x00\x12\x13\n" +
	"\x0fADMIN_NOT_FOUND\x10\x01\x12\x17\n" +
	"\x13INVALID_CREDENTIALS\x10\x02\x12\x19\n" +
	"\x15INVALID_IDENTITY_TYPE\x10\x03\x12\x13\n" +
	"\x0fUNAUTHENTICATED\x10\x04\x12\x15\n" +
	"\x11PERMISSION_DENIED\x10\x05\x12\x14\n" +
	"\x10INVALID_ADMIN_ID\x10\x06BQ\n" +
	"\x13api.kratos.admin.v1P\x01Z8github.com/go-kratos/kratos-admin/api/kratos/admin/v1;v1b\x06proto3"

var (
	file_kratos_admin_v1_error_reason_proto_rawDescOnce sync.Once
	file_kratos_admin_v1_error_reason_proto_rawDescData []byte
)

func file_kratos_admin_v1_error_reason_proto_rawDescGZIP() []byte {
	file_kratos_admin_v1_error_reason_proto_rawDescOnce.Do(func() {
		file_kratos_admin_v1_error_reason_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_kratos_admin_v1_error_reason_proto_rawDesc), len(file_kratos_admin_v1_error_reason_proto_rawDesc)))
	})
	return file_kratos_admin_v1_error_reason_proto_rawDescData
}

var file_kratos_admin_v1_error_reason_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_kratos_admin_v1_error_reason_proto_goTypes = []any{
	(ErrorReason)(0), // 0: kratos.admin.v1.ErrorReason
}
var file_kratos_admin_v1_error_reason_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_kratos_admin_v1_error_reason_proto_init() }
func file_kratos_admin_v1_error_reason_proto_init() {
	if File_kratos_admin_v1_error_reason_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_kratos_admin_v1_error_reason_proto_rawDesc), len(file_kratos_admin_v1_error_reason_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_kratos_admin_v1_error_reason_proto_goTypes,
		DependencyIndexes: file_kratos_admin_v1_error_reason_proto_depIdxs,
		EnumInfos:         file_kratos_admin_v1_error_reason_proto_enumTypes,
	}.Build()
	File_kratos_admin_v1_error_reason_proto = out.File
	file_kratos_admin_v1_error_reason_proto_goTypes = nil
	file_kratos_admin_v1_error_reason_proto_depIdxs = nil
}
